version: "3.7"

services:

  building-maker:
    container_name: building-maker
    image: building-maker:latest
    build:
      context: .
      dockerfile: Dockerfile
    # We don't need this port open in prod, but if you do:
    #ports:
    #  - "127.0.0.1:9054:9054"

networks:
  default:
    name: tz1and_prod